### PR TITLE
#171380780 rate an accommodation 

### PR DESCRIPTION
**Pull request by Ugizwenayo-Divine**
### What does this PR ​ do​ ? 
- give rates to an accommodation you have traveled to

### Description of Task to be completed?
- create a rating model
- create handleRatingAccommodation function in `./src/services/accommodation.service.js file`
- create rateAccommodation function in `./src/controllers/accommodation.controller.js file`
- create rating Accommodation route in `./src/routes/api/accommodation.routes.js file`
- Have the following API route:
`POST /api/accommodations/rates`

### How should this be manually tested?
- After cloning the project repo, run `npm i` inside the cloned repo folder
- Make sure to rename .env.example to .env, 
- In .env file, provide all values for variables under `#Development database`  and `#General`
- Finally, run the following commands respectively:
`git fetch`
`git checkout ft-rate-accommodation-171380780`
`npm i`
`npm run migrations`
- If the above steps have been followed correctly, 
you should see a rating table created in your database
- Insert an accommodation in the database by running `npm run seed` 
- create a trip request 
- book accommodation for the trip request you created
- on `http://<your_server_hostname>:<server_port>/api/accommodations/rates` send
>"requestId":1
>"rates": 4
- on `http://<your_server_hostname>:<server_port>/api/accommodations/rates/:id` 
>provide the id of rated accommodation

## Any background context you want to provide?
- You must create an account and use the obtained token as an `authorization header`

### What are the relevant pivotal tracker stories?
[ #171380780](https://www.pivotaltracker.com/story/show/171380780)

### Screenshots 
accommodationRated

didNotBook

beforeDate

invalidRate

invalidRequestId

NotExistRequest

notRatesOwner

ratedRequest

### Questions:
N/A

### CODE REVIEW

**Review by Muhire-Josue — APPROVED** [review]
LGTM great job @Ugizwenayo-Divine

**Review by muchristian — APPROVED** [review]
Great job @Ugizwenayo-Divine

**Comment by kipropbrian** [comment]
You have this error. The table name changed if I am not wrong.
```
{
    "error": {
        "name": "SequelizeForeignKeyConstraintError",
        "parent": {
            "name": "error",
            "length": 282,
            "severity": "ERROR",
            "code": "23503",
            "detail": "Key (accommodationId)=(1) is not present in table \"accommodation\".",
            "schema": "public",
            "table": "ratings",
            "constraint": "ratings_accommodationId_fkey",
            "file": "ri_triggers.c",
            "line": "2783",
            "routine": "ri_ReportViolation",
            "sql": "INSERT INTO \"ratings\" (\"requestId\",\"accommodationId\",\"createdBy\",\"rates\",\"updatedAt\",\"createdAt\") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *;",
            "parameters": [
                "2",
                1,
                5,
                "3",
                "2020-05-07 12:27:05.374 +00:00",
                "2020-05-07 12:27:05.374 +00:00"
            ]
        },
  }
```

**Review by descholar-ceo — APPROVED** [review]
This so good @Ugizwenayo-Divine, I liked that your codes are clean, and you tried to adapt to the new OOP syntax on services, that is so good, I wish you to keep up, special congrats.

**Pull request merged**
