### PR TITLE
#171380764 search trip requests

### PR DESCRIPTION
**Pull request by since9629**
#### What does this PR do?
Creates API endpoint used to search trip requests
#### Description of Task to be completed?
- create API endpoint at ***GET /api/trips/search***
#### How should this be manually tested?
- After cloning the project repo, run `npm i` inside the cloned repo folder
- Make sure to rename .env.example to .env, 
- In .env file, provide all values for variables under `#Development database`  and `#General`
- Finally, run the following commands respectively:
`git fetch`
`git checkout ft-search-trip-requests-171380764`
`npm i`
`npx sequelize-cli db:create`
`npx sequelize-cli db:migrate`
`npm run start`
- If the above steps have been followed correctly, you should see a new users and trips table created in your database
- To search trip requests, send this request to the API, `GET http://<your_server_hostname>:<server_port>/api/trips/search?field=travelFrom&search=Butare&limit=5&offset=0`:
#### Any background context you want to provide?
You need to create an account and use the obtained token as an `authorization header` in your requests to the API.
#### What are the relevant pivotal tracker stories?
[#171380764](https://www.pivotaltracker.com/n/projects/2435482/stories/171380764)
#### Screenshots (if appropriate)
Example request & response:
SharedScreenshot

### CODE REVIEW

**Review by descholar-ceo — COMMENTED** [review]
I am trying to search some data that I have in db, and it is returning empty array; is that normal?

### This is the response that I am getting
Screenshot from 2020-03-30 11-30-45

### This is what I have in my database
Screenshot from 2020-03-30 11-33-06

**Review by Muhire-Josue — APPROVED** [review]
LGTM

**Comment by since9629** [comment]
> I am trying to search some data that I have in db, and it is returning empty array; is that normal?
> 
> ### This is the response that I am getting
> Screenshot from 2020-03-30 11-30-45
> 
> ### This is what I have in my database
> Screenshot from 2020-03-30 11-33-06

Yes @de-scholar it's how it is supposed to work. The reason you couldn't see any data is because you(the current user) haven't made a trip request with `travelFrom = Kigali`. The records you see in db were created by a different user(not current user), therefor you can't search another user's trip requests, only yours.

**Review by muchristian — APPROVED** [review]
Well done

**Review by Ugizwenayo-Divine — COMMENTED** [review]
great job @karamuka but I think it would be better if you check those things. 
I've seen that a user can search for trips where a return date is null
I think you can allow that option

**Review by descholar-ceo — APPROVED** [review]

**Comment by since9629** [comment]
> great job @karamuka but I think it would be better if you check those things.
> I've seen that a user can search for trips where a return date is null
> I think you can allow that option

It's been taken care of, @Ugizwenayo-Divine

**Review by mifeille — APPROVED** [review]

**Pull request merged**
