### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by Muhire-Josue**
#### What does this PR do?

- It moves the Morgan module from dev dependencies to dependencies

#### Description of Task to be completed?

- It fixes Heroku error by moving Morgan dependency from dev to global

#### How should this be manually tested?

- On this PR you will find a "View deployment", click on it.

- You should see this message { message: 'welcome' }

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

- N/A

#### Screenshots (if appropriate)

- N/A

### CODE REVIEW

**Review by descholar-ceo — APPROVED** [review]
It is actually working and seems to me that the bug is fixed successfully

**Review by descholar-ceo — COMMENTED** [review]
Something that I am thinking about is that you specified that To test this PR, I need to clone it and `npm run dev` locally, but honestly locally there was no any issue, the actual issue was the deployment on heroku, I think you should state how to test if the bug has been fixed by testing its deployment.

**Review by ricahcyuzuzo — APPROVED** [review]
Great!

**Review by the22mastermind — APPROVED** [review]
Awesome work @Muhire-Josue Keep it up.

**Pull request merged**
