### PR TITLE
#171380741 Setup API documentation

### PR DESCRIPTION
**Pull request by the22mastermind**
#### What does this PR do?
Setup API documentation using Swagger
#### Description of Task to be completed?
* Initialize an express server in index.js file
* Create a basic swagger.json spec file
* Install `express`, `swagger-ui-express` and `babel` libraries
* Create a sample route at `/api/v1`
* Create `.babelrc` file
#### How should this be manually tested?
1. Open your terminal and run `git clone https://github.com/Stackup-Rwanda/stackup2-barefoot-backend/`
2. run `cd stackup2-barefoot-backend` to go into the root directory of the project
3. run `git checkout -b ch-setup-api-documentation-171380741 origin/ch-setup-api-documentation-171380741` to pull this branch and switch to it
4. run `npm install` to install the dependencies
5. run `npm run dev` to start the server
6. Open your browser and navigate to this link: [localhost:3000/public/api-docs](http://localhost:3000/public/api-docs)
7. Click on the highlighted `GET` route, then click on the `Try it out` button then `execute` button and you should see a server response of status `200` and a message of `Welcome!` 
#### Any background context you want to provide?
* You need to install [Node.js](https://nodejs.org/en/) and [git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) before testing.
#### What are the relevant pivotal tracker stories?
[#171380741](https://www.pivotaltracker.com/story/show/171380741)
#### Screenshots (if appropriate)
N/A
#### Questions:

### CODE REVIEW

**Review by ricahcyuzuzo — APPROVED** [review]
This Work Loog Good to me, Keep it up!

**Review by ricahcyuzuzo — COMMENTED** [review]
@the22mastermind Would you change the app.js to index.js, I mean take your codes from app.js and move them into src/index.js to make it the same as Josue! It will be better!

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
You did really a great job, but I am a bit concerned with the conflicts your branch has with develop, could you solve theconflicts?

**Comment by the22mastermind** [comment]
Thank you so much for reviewing my work. I am working on your feedback, I will reach out to you soon for another review. 🚀

**Review by Muhire-Josue — COMMENTED** [review]
Great work bro. can you squash your commits into one? Also it seems like your commits don't have a header. something like chore(swagger). Please consider adding a header in your commits messages.

**Pull request closed without merging**
